services:
  - type: web
    name: packet-sniffer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python runner.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9